<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="4" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="9432" started-at="2019-07-24T09:25:56Z" finished-at="2019-07-24T09:26:05Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="9432" started-at="2019-07-24T09:25:56Z" finished-at="2019-07-24T09:26:05Z">
      <class name="com.testcases.FacilityViewTests">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.testcases.FacilityViewTests@14dd9eb7]" name="beforeSuite" is-config="true" duration-ms="91" started-at="2019-07-24T09:25:56Z" finished-at="2019-07-24T09:25:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.testcases.FacilityViewTests@14dd9eb7]" name="setUp" is-config="true" duration-ms="6193" started-at="2019-07-24T09:25:56Z" finished-at="2019-07-24T09:26:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test1()[pri:1, instance:com.testcases.FacilityViewTests@14dd9eb7]" name="test1" duration-ms="898" started-at="2019-07-24T09:26:02Z" description="Test case 1" finished-at="2019-07-24T09:26:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.testcases.FacilityViewTests.test1(FacilityViewTests.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="wrapUp()[pri:0, instance:com.testcases.FacilityViewTests@14dd9eb7]" name="wrapUp" is-config="true" duration-ms="2323" started-at="2019-07-24T09:26:03Z" finished-at="2019-07-24T09:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrapUp -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.testcases.FacilityViewTests@14dd9eb7]" name="afterSuite" is-config="true" duration-ms="156" started-at="2019-07-24T09:26:05Z" finished-at="2019-07-24T09:26:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.testcases.FacilityViewTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
