<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INMAAWN5384001" ignored="4" name="Test" tests="1" failures="1" timestamp="24 Jul 2019 09:26:05 GMT" time="9.432" errors="0">
  <testcase name="test1" time="0.898" classname="com.testcases.FacilityViewTests">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.testcases.FacilityViewTests.test1(FacilityViewTests.java:67)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test3" time="0.0" classname="com.testcases.HomePageTests">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.0" classname="com.testcases.FacilityViewTests">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase name="checkWhetherGlobalViewIsSelectedByDefault" time="0.0" classname="com.testcases.FacilityViewTests">
    <ignored/>
  </testcase> <!-- checkWhetherGlobalViewIsSelectedByDefault -->
  <testcase name="validateEnteringShipmentID" time="0.0" classname="com.testcases.FacilityViewTests">
    <ignored/>
  </testcase> <!-- validateEnteringShipmentID -->
</testsuite> <!-- Test -->
